<?php
/**
 * Template Name: RCC Home Page
 *
 * This is the template that displays the RCC Home Page
 * Version: 11.0.0
 *
 * @package WordPress
 * @subpackage Awaken_Benehime
 * @since Awaken Benehime V11
 */

get_header(); ?>

<div id="primary" class="site-content">
	<div id="content" role="main">
		<div class="billboard blue30 no-hover billboard-full-width" id="billboard">
			<?php while ( have_posts() ) : the_post(); ?>
				<?php the_content(); ?>
			<?php endwhile; // end of the loop. ?>
			<?php //echo get_new_royalslider(1); ?>
		</div><!-- .billboard -->
	 	<div id="container-cubes" class="container container-cubes clearfix">
			<?php
			$args= array(
					'post_type'=>'cubes',
					'posts_per_page'  => -1,
					'meta_key' => 'cube_id',
					'orderby'  =>'meta_value_num',
					'order' => 'ASC',
			);
			$cubes_query = new WP_Query($args);
			$cubes = [];
			if ($cubes_query->have_posts()) : while($cubes_query->have_posts()) : $cubes_query->the_post();

					$id = $cubes_query->post->ID;
					$cube_id = esc_html( get_post_meta( $id,'cube_id', true ) );

					//This removes the autogenerated <p> tags that wordpress wraps
					//content with in the TinyMCE editor for the cubes on this page
					remove_filter('the_content', 'wpautop');

					$cubes[$cube_id] = [
							'cube_id' => $cube_id,
							'post_id' => $id,
							'cube_enable_url' => esc_html( get_post_meta( $id,'cube_enable_url', true ) ),
							'cube_url' => esc_html( get_post_meta( $id,'cube_url', true ) ),
							'cube_color' => esc_html( get_post_meta( $id,'cube_color', true ) ),
							'cube_class' => esc_html( get_post_meta( $id,'cube_class', true ) ),
							'cube_title' => get_the_title(),
							'cube_content' => apply_filters('the_content',get_the_content()),
							'cube_is_countdown' => esc_html( get_post_meta( $id,'cube_is_countdown', true ) ),
							'cube_countdown_date' => esc_html( get_post_meta( $id,'cube_countdown_date', true ) ),
							'has_thumbnail' => has_post_thumbnail( $id ),
							'cube_width' => esc_html( get_post_meta( $id,'cube_width', true ) ),
							'cube_height' => esc_html( get_post_meta( $id,'cube_height', true ) )
					];

					endwhile; else: ?>
					<p><?php _e('Sorry, no posts matched your criteria.'); ?></p>
			<?php endif; ?>

			<?php
				foreach ( $cubes as $cube ) {
					ab11_cubes_output( $cube );
				}
			?>
		</div><!--end .container-cubes -->
		<div id="container-highlights" class="container container-cubes clear-left clearfix">
			<div class="grid-3 highlight-title">
					<h2 class="no-margin">Living in the spotlight</h2>
					<p class="tagline no-margin">A look into the life of <em>your</em> RCC.</p>
			</div>
			<?php
			global $switched;
      
   
      	$new_blog_id = 2;
      	$category = 3;
    
      	// $new_blog_id = 25;
      	// $category = 25;
      

      switch_to_blog( $new_blog_id );
      $args = (array(
        'showposts' => 3,
				'category' => $category
      ));
      $posts = get_posts($args);

      if($posts){
	      foreach($posts as $post){
	        setup_postdata($post);
					$default_attr = array(
						'class'	=> "attachment",
						'alt'	=> trim(strip_tags( $post->post_title )),
						'title'	=> trim(strip_tags( $post->post_title )),
						'width' => 'auto',
						'height' => 'auto'
					);
					$image_url = wp_get_attachment_image_src( get_post_thumbnail_id($post->ID), 'thumbnail');
					if (has_post_thumbnail()) {
					echo '<div class="cube rcc-blue grid-3 highlight">'.'<a href="' . get_permalink() .'""><img class="highlight-img" src="'.$image_url[0].'" alt="'.get_the_title().'" /></a>'.
							 '<a href="' . get_permalink() . '" class="highlight-headline" title="Posted '. get_the_time("j F Y | g:i a"). '">'.
							 get_the_title().'</a></div>';
					}
					else {
						echo '<div class="cube rcc-blue grid-3 highlight">'.'<a href="' . get_permalink() .'"">'.
							 '<img class="highlight-img" src="/wp-content/themes/css/images/default_thumb.png" alt="' . $posts[$i]->post_title . '" /></a>'.
							 '<a href="' . get_permalink() . '" class="highlight-headline" title="Posted '. get_the_time("j F Y | g:i a"). '">'.
							 get_the_title().'</a></div>';
					}

	      }
      }

      restore_current_blog();
      ?>
		</div><!-- .container-highlights -->
	</div><!-- #content -->
</div><!-- #primary -->
<?php get_footer(); ?>




